kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    config.openshift.io/inject-proxy: csi-driver
    config.openshift.io/inject-proxy-cabundle: csi-driver
spec:
  template:
    metadata:
      annotations:
        openshift.io/required-scc: restricted-v2
      labels:
        openshift.storage.network-policy.dns: allow
        openshift.storage.network-policy.api-server: allow
        openshift.storage.network-policy.metrics-range: allow
        openshift.storage.network-policy.all-egress: allow
    spec:
      ## Removing this for now
      # hostNetwork: true # although not needed for other drivers, this is required for the Azure File driver
      containers:
        - name: csi-driver
          image: ${DRIVER_IMAGE}
          imagePullPolicy: IfNotPresent
          args:
            - --enable-vhd=false
            - --endpoint=$(CSI_ENDPOINT)
            - --logtostderr
            - --metrics-address=localhost:${DRIVER_METRICS_PORT}
            - --v=${LOG_LEVEL}
            # Use credentials provided by the azure-inject-credentials container
            - --cloud-config-secret-name=""
            - --cloud-config-secret-namespace=""
            # TODO: make sure this is needed. Taken from upstream
            - --user-agent-suffix=OSS-kubectl
          env:
            - name: AZURE_CREDENTIAL_FILE
              value: "/etc/kubernetes/cloud.conf"
            - name: CSI_ENDPOINT
              value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
            - name: AZCOPY_LOG_LOCATION
              value: /tmp/azcopy
            - name: AZCOPY_JOB_PLAN_LOCATION
              value: /tmp/azcopy
          ports:
            - name: healthz
              containerPort: 10303
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 5
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
            - name: cloud-config
              mountPath: /etc/kubernetes/
              readOnly: true
            - name: bound-sa-token
              mountPath: /var/run/secrets/openshift/serviceaccount
              readOnly: true
          resources:
            requests:
              memory: 50Mi
              cpu: 10m
          terminationMessagePolicy: FallbackToLogsOnError
      volumes:
        - name: metrics-serving-cert
          secret:
            secretName: azure-file-csi-driver-controller-metrics-serving-cert

