kind: DaemonSet
apiVersion: apps/v1
metadata:
  annotations:
    config.openshift.io/inject-proxy: csi-driver
    config.openshift.io/inject-proxy-cabundle: csi-driver
spec:
  template:
    spec:
      hostNetwork: true
      containers:
        - name: csi-driver
          securityContext:
            privileged: true
          image: ${DRIVER_IMAGE}
          imagePullPolicy: IfNotPresent
          args:
            - --endpoint=$(CSI_ENDPOINT)
            - --logtostderr
            - --nodeid=$(KUBE_NODE_NAME)
            - --user-agent-suffix=OSS-kubectl
            - --v=${LOG_LEVEL}
            # Use credentials provided by the azure-inject-credentials container
            - --cloud-config-secret-name=""
            - --cloud-config-secret-namespace=""
          env:
            - name: AZURE_CREDENTIAL_FILE
              value: "/etc/kubernetes/cloud.conf"
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          resources:
            requests:
              memory: 50Mi
              cpu: 10m
          terminationMessagePolicy: FallbackToLogsOnError
          ports:
            - name: healthz
              # Due to hostNetwork, this port is open on all nodes!
              containerPort: 10302
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 5
          volumeMounts:
          - mountPath: /csi
            name: socket-dir
          - mountPath: /var/lib/kubelet
            mountPropagation: Bidirectional
            name: kubelet-dir
          - mountPath: /etc/kubernetes/
            readOnly: true
            name: cloud-config
          - mountPath: /dev
            name: device-dir
          - mountPath: /sys/bus/scsi/devices
            name: sys-devices-dir
          - mountPath: /sys/class/scsi_host/
            name: scsi-host-dir
          - mountPath: /etc/selinux
            name: etc-selinux
          - mountPath: /sys/fs
            name: sys-fs
          - name: bound-sa-token
            mountPath: /var/run/secrets/openshift/serviceaccount
            readOnly: true
      initContainers:
        # Merge /etc/kubernetes/cloud.conf (on the host) with secret "azure-file-credentials" into "merged-cloud-config" emptydir.
        - name: azure-inject-credentials
          image: ${CLUSTER_CLOUD_CONTROLLER_MANAGER_OPERATOR_IMAGE}
          command:
            - /azure-config-credentials-injector
          args:
            - --cloud-config-file-path=/etc/cloud-config/config
            - --output-file-path=/etc/merged-cloud-config/cloud.conf
            # Force disable node's managed identity, azure-file-credentials Secret should be used.
            - --disable-identity-extension-auth
            - --enable-azure-workload-identity=${ENABLE_AZURE_WORKLOAD_IDENTITY}
            - --creds-path=/etc/azure/credentials
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - name: src-cloud-config
              mountPath: /etc/cloud-config
              readOnly: true
            - name: cloud-config
              mountPath: /etc/merged-cloud-config
            - name: cloud-sa-volume
              readOnly: true
              mountPath: /etc/azure/credentials
      volumes:
        - name: src-cloud-config
          configMap:
            name: azure-cloud-config
        - name: cloud-sa-volume
          secret:
            secretName: azure-file-credentials
        - hostPath:
            path: /sys/bus/scsi/devices
            type: Directory
          name: sys-devices-dir
        - hostPath:
            path: /sys/class/scsi_host/
            type: Directory
          name: scsi-host-dir
        - emptydir: {}
          name: cloud-config
        - name: bound-sa-token
          projected:
            sources:
              - serviceAccountToken:
                  path: token
                  audience: openshift

