apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: openshift-aws-efs-csi-driver-node
  namespace: openshift-cloud-credential-operator
  annotations:
    credentials.openshift.io/role-arns-vars: NODE_ROLEARN
spec:
  secretRef:
    # The name must have "node" string *close to the beginning*.
    # CCO will create a role <cluster name>-<namespace>-<secret name>, and it truncates it at 64 characters.
    # We want to get -node- in the role name, so it does not collide with the controller name.
    name: node-aws-efs-cloud-credentials
    namespace: openshift-cluster-csi-drivers
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
    - effect: Allow
      action:
      - elasticfilesystem:DescribeMountTargets
      - ec2:DescribeAvailabilityZones
      resource: "*"
